//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardgameManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoardgameDBEntities : DbContext
    {
        public BoardgameDBEntities()
            : base("name=BoardgameDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boardgame> Boardgames { get; set; }
        public virtual DbSet<BoardgameCall> BoardgameCalls { get; set; }
        public virtual DbSet<BoardGameType> BoardGameTypes { get; set; }
    }
}
